
services:
  plex:
#    image: ghcr.io/hotio/plex
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ=Europe/Kyiv
#      - PLEX_CLAIM_TOKEN=claim-x5-cnD36ztxCzRzz3r4g
      - PLEX_CLAIM=claim-x5-cnD36ztxCzRzz3r4g
      - ADVERTISE_IP=http://192.168.88.112:32400
      - PUID=1000
      - PGID=1000
      - UMASK=002
#      - VERSION=docker
    # devices:
    # - /dev/dri:/dev/dri # for hardware transcoding intel igpu
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/docker/plex/database:/config
      - /dev/shm:/transcode #ram transcoding
      - /mnt/media:/data
#    hostname: subdomain.user.ru
    ports: # uncomment if not using reverse proxy
      - 32400:32400/tcp #open if you have problems with local access
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true