services:
  monitoring:
    image: nicolargo/glances:latest
    restart: always
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    environment:
      - TZ=Europe/Kyiv
      - "GLANCES_OPT=-w"