services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports: #uncomment if not using reverse proxy
      - 8000:8000
      - 9443:9443
      - 9000:9000 # for http
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/user/docker/portainer/data:/data
    restart: unless-stopped
    networks:
      proxy:


networks:
  proxy:
    external: true